config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  resources :users, :only => [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, :uniqueness => true, :presence => true
    validates :firstName, :presence => true
    validates :lastName, :presence => true
    validates :pets, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save 
      redirect_to root_path #dd
    else
      render :new 
    end
  end

  private
  def user_params
    params.require(:user).permit(:firstName, :lastName, :email, :pets)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <title>PetCloning</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <%= link_to 'Home', root_path %> |
      <%= link_to 'All users', users_path %>

      <%= yield %>

    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="dogs-running"> 
  <h1 class="AGP"> AGP Pet Cloning Service</h1>
  <p>A lifetime relationship with your pet</p>
  <button type="button" class="btn btn-success">Learn More</button>
</div>

<div class='animals-logos'>
    <div class="catson">
        <img id="cat" src="https://images.unsplash.com/photo-1573865526739-10659fec78a5?crop=entropy&cs=tinysrgb&fm=jpg&ixid=Mnw3MjAxN3wwfDF8c2VhcmNofDJ8fGNhdHxlbnwwfHx8fDE2NjE3ODY5NDk&ixlib=rb-1.2.1&q=80&q=85&fmt=jpg&crop=entropy&cs=tinysrgb&w=450" alt="cat">
        <p>Cat cloning</p>
    </div>    
    <div class="dogson">
        <img id="dog" src="https://images.unsplash.com/photo-1587300003388-59208cc962cb?crop=entropy&cs=tinysrgb&fm=jpg&ixid=Mnw3MjAxN3wwfDF8c2VhcmNofDV8fGRvZ3xlbnwwfHx8fDE2NjE3ODczNzg&ixlib=rb-1.2.1&q=80&q=85&fmt=jpg&crop=entropy&cs=tinysrgb&w=450" alt="dog">
        <p>Dog cloning</p>
    </div>
    <div class="horseon">
        <img id="horse" src="https://images.unsplash.com/photo-1546894239-c9865f479ad0?crop=entropy&cs=tinysrgb&fm=jpg&ixid=Mnw3MjAxN3wwfDF8c2VhcmNofDM5fHxIb3JzZXxlbnwwfHx8fDE2NjE4MzY5NTU&ixlib=rb-1.2.1&q=80&q=85&fmt=jpg&crop=entropy&cs=tinysrgb&w=450" alt="horse">
        <p>Horse cloning</p>
    </div>
</div>

<h1 id="latest-posts">Our latest posts:</h1>
<div class="our-latest-post">
    <div class="man-and-dog">
        <img src="https://images.unsplash.com/photo-1644675272883-0c4d582528d8?crop=entropy&cs=tinysrgb&fm=jpg&ixid=Mnw3MjAxN3wwfDF8c2VhcmNofDMzfHxkb2N0b3IlMjB3aXRoJTIwYSUyMGRvZ3xlbnwwfHx8fDE2NjE4Mzg2ODY&ixlib=rb-1.2.1&q=80&q=85&fmt=jpg&crop=entropy&cs=tinysrgb&w=450" alt="9">
        <p>Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet</p>
    </div>
    <div class="cat-hug">
        <img src="https://images.unsplash.com/photo-1607430540778-b8c293209f7b?crop=entropy&cs=tinysrgb&fm=jpg&ixid=Mnw3MjAxN3wwfDF8c2VhcmNofDUyfHx0d28lMjBjYXRzfGVufDB8fHx8MTY2MTgzOTE5NA&ixlib=rb-1.2.1&q=80&q=85&fmt=jpg&crop=entropy&cs=tinysrgb&w=450" alt="cat hugging">
        <p>Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet</p>
    </div>
    <div class="horse-kickingback">
        <img src="https://images.unsplash.com/photo-1465418028868-159acdc7747f?crop=entropy&cs=tinysrgb&fm=jpg&ixid=Mnw3MjAxN3wwfDF8c2VhcmNofDI5fHx0d28lMjBob3JzZXN8ZW58MHx8fHwxNjYxODM5Mjkw&ixlib=rb-1.2.1&q=80&q=85&fmt=jpg&crop=entropy&cs=tinysrgb&w=450" alt="horse just chilling">
        <p>Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet</p>
    </div>
</div>

<div class="lead-tech">
  <hr>
  <i class="bi bi-gear-wide-connected"></i>
  <h2>Leading Technology</h2>
  <hr>

  <hr>
  <i class="bi bi-people-fill"></i>
  <h2>Personal Team & Services</h2>
  <hr>

  <hr>
  <i class="bi bi-tropical-storm"></i>
  <h2>Genetic Identification Team</h2>  
  <hr>    

  <hr>
  <i class="bi bi-airplane-engines"></i>
  <h2>Mission of Hope & Commitment</h2>
  <hr>
</div>

<h2 id="testimonials">Client Testimonials:</h2>
<div id="carouselExampleInterval" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active" data-interval="10000">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
      </div>

      <div class="carousel-item" data-interval="2000">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
      </div>

      <div class="carousel-item">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
      </div>
    </div>

    <button class="carousel-control-prev" type="button" data-target="#carouselExampleInterval" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </button>

    <button class="carousel-control-next" type="button" data-target="#carouselExampleInterval" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </button>
</div>

<h2 id="hello">Hello There Pet Lover</h2>

<p>Want to recieve our latests posts, news and discounts, Sign Up!!</p>

<p>I only want to receive news on:</p>

<%= link_to 'Sign Up!', new_user_path, :class => "btn btn-success", :id => "signup" %>

<div id="personal-info">
<p>We will protect your personal information</p>
<a id="privacy" href="#">read our privacy policy</a>
<p>We won't spam you we promise!</p>
</div>

<div class="footer">
    <div>
      <h2>About Us</h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
    </div>

    <div>
      <h2>Our Services</h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
    </div>

    <div>
      <h2>Contact Us</h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
    </div>  
</div>

app/views/users/index.html.erb
<h1>All users</h1>

<h2><%= @users.count %> registered users</h2>


 <table>
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Pets</th>
    </tr>

    <% @users.each do |user|%>
    <tr class="allusers">
        <td><%= user.firstName %></td>
        <td><%= user.email %></td>
        <td><%= user.pets %></td>
    </tr>
    <% end %>

</table> 

app/views/users/new.html.erb
<h1>WELCOME</h1>

<% if @user.errors.any? %>
    <ol>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ol>
<% end %>

<%= form_for @user do |f| %>
    <div class="form-group">
        <%= f.label :firstName%>
        <%= f.text_field :firstName, :class=> 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :lastName %>
        <%= f.text_field :lastName, :class=> 'form-control' %>
    </div>


    <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, :class => 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :pets %>
        <%= f.text_field :pets, :class => 'form-control' %>
    </div>

    <%= f.submit "Sign up!", :class => 'btn btn-info' %>
<% end %>